### ISSUE TITLE
Отрефакторить функцию createElement

### ISSUE THREAD

**Issue by llallonen** [amgSTRIDeR/RS-Clone#10]
Избегать постоянного использования innerHTML
Рассматриваемый вариант

<details>
<summary>Details</summary>

```
const createElement = <T extends HTMLElement>(
  node: string,
  classNames?: string[],
  content?: string,
): T => {
  const element = document.createElement(node) as T;
  if (classNames && classNames.length > 0) {
    element.classList.add(...classNames);
  }

  if (content) {
    element.innerHTML = content;
  }
  return element;
};

export default createElement;
```

</details>
Использование:
```const buttonRu = createElement('div', ['w-[40px]', 'cursor-pointer'], HeaderSVG.Ru);```

**Comment by amgSTRIDeR** [comment]
Можно еще id добавить - ```const buttonRu = createElement('div', ['w-[40px]', 'cursor-pointer'], HeaderSVG.Ru, id);```

**Comment by llallonen** [comment]
Выполнено https://github.com/amgSTRIDeR/RS-Clone/pull/9/files
